name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          export GEM_HOME=$HOME/.gem
          export PATH=$GEM_HOME/bin:$PATH
          gem install cocoapods --user-install
          gem which cocoapods
          pod install
          xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld CONFIGURATION_BUILD_DIR=`pwd`/build clean build | xcpretty && exit ${PIPESTATUS[0]}
      - name: Run
        run: |
          ./build/HelloWorld 
