name: Xcode - Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tools
        run: |
          export GEM_HOME=$HOME/.gem
          export PATH=$GEM_HOME/bin:$GEM_HOME/ruby/2.7.0/bin:$PATH
          gem install cocoapods --user-install
          pod install
      - name: Build
        run: |
          xcodebuild -workspace HelloWorld.xcworkspace -scheme HelloWorld CONFIGURATION_BUILD_DIR=`pwd`/build clean build
      - name: Run
        run: |
          build/HelloWorld 
